app/api/urls.py
from django.urls import path, include
from .views import ProductoList, ProductoDetalle, \
    ClienteList

urlpatterns = [
    path('v1/productos/',ProductoList.as_view(),name='producto_list'),
    path('v1/productos/<str:codigo>',ProductoDetalle.as_view(),name='producto_detalle'),
    path('v1/clientes/',ClienteList.as_view(),name='cliente_list')
]

app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path('',include(('bases.urls','bases'), namespace='bases')),
    path('inv/',include(('inv.urls','inv'), namespace='inv')),
    path('cmp/', include(('cmp.urls', 'cmp'), namespace='cmp')),
    path('fac/', include(('fac.urls', 'fac'), namespace='fac')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app/bases/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from bases.views import Home, HomeSinPrivilegios

from .views import *


urlpatterns = [
    path('',Home.as_view(), name='home'),
    path('login/',auth_views.LoginView.as_view(template_name='bases/login.html'),
        name='login'),
    
    
    path('logout/',auth_views.LogoutView.as_view(template_name='bases/login.html'),
         name='logout'),

    path('sin_privilegios/',
         HomeSinPrivilegios.as_view(),
         name='sin_privilegios'),
    
    path('idiomas/',IdiomaList.as_view(),name="idiomas"),
    path('frases/',FraseList.as_view(),name="frases"),
]

app/inv/urls.py
from django.urls import path

from .views import CategoriaView, CategoriaNew, CategoriaEdit, \
    CategoriaDel, \
    SubCategoriaView, SubCategoriaNew, SubCategoriaEdit, SubCategoriaDel, \
    MarcaView, MarcaNew, MarcaEdit, marca_inactivar, \
    UMView, UMNew, UMEdit, um_inactivar,\
    ProductoView, ProductoEdit, ProductoNew, producto_inactivar

urlpatterns = [
    path('categorias/',CategoriaView.as_view(), name='categoria_list'),
    path('categorias/new',CategoriaNew.as_view(), name='categoria_new'),
    path('categorias/edit/<int:pk>',CategoriaEdit.as_view(), name='categoria_edit'),
    path('categorias/delete/<int:pk>',CategoriaDel.as_view(), name='categoria_del'),

    path('subcategorias/',SubCategoriaView.as_view(), name='subcategoria_list'),
    path('subcategorias/new',SubCategoriaNew.as_view(), name='subcategoria_new'),
    path('subcategorias/edit/<int:pk>',SubCategoriaEdit.as_view(), name='subcategoria_edit'),
    path('subcategorias/delete/<int:pk>',SubCategoriaDel.as_view(), name='subcategoria_del'),

    path('marcas/',MarcaView.as_view(), name="marca_list"),
    path('marcas/new',MarcaNew.as_view(), name="marca_new"),
    path('marcas/edit/<int:pk>',MarcaEdit.as_view(), name="marca_edit"),
    path('marcas/inactivar/<int:id>',marca_inactivar, name="marca_inactivar"),

    path('um/',UMView.as_view(), name="um_list"),
    path('um/new',UMNew.as_view(), name="um_new"),
    path('um/edit/<int:pk>',UMEdit.as_view(), name="um_edit"),
    path('um/inactivar/<int:id>',um_inactivar, name="um_inactivar"),

    path('productos/',ProductoView.as_view(), name="producto_list"),
    path('productos/new',ProductoNew.as_view(), name="producto_new"),
    path('productos/edit/<int:pk>',ProductoEdit.as_view(), name="producto_edit"),
    path('productos/inactivar/<int:id>',producto_inactivar, name="producto_inactivar"),
]

app/bases/models.py
from django.db import models

from django.contrib.auth.models import User
from django_userforeignkey.models.fields import UserForeignKey


class ClaseModelo(models.Model):
    estado = models.BooleanField(default=True)
    fc = models.DateTimeField(auto_now_add=True)
    fm = models.DateTimeField(auto_now=True)
    uc = models.ForeignKey(User, on_delete=models.CASCADE)
    um = models.IntegerField(blank=True,null=True)

    class Meta:
        abstract=True


class ClaseModelo2(models.Model):
    estado = models.BooleanField(default=True)
    fc = models.DateTimeField(auto_now_add=True)
    fm = models.DateTimeField(auto_now=True)
    # uc = models.ForeignKey(User, on_delete=models.CASCADE)
    # um = models.IntegerField(blank=True,null=True)
    uc = UserForeignKey(auto_user_add=True,related_name='+')
    um = UserForeignKey(auto_user=True,related_name='+')

    class Meta:
        abstract=True



class Idioma(models.Model):
    nombre = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = "Idiomas"

    def __str__(self):
        return self.nombre


class Frase(models.Model):
    idioma = models.ForeignKey(Idioma,on_delete=models.CASCADE)
    autor = models.CharField(max_length=50,default="Anónimo")
    frase = models.TextField(null=True,blank=True)

    class Meta:
        verbose_name_plural = "Frases"

    def __str__(self):
        return "{} - {}".format(self.autor,self.idioma)

app/bases/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse_lazy

from django.contrib.auth.mixins import LoginRequiredMixin,\
     PermissionRequiredMixin
from django.views import generic

from .models import Idioma,Frase

class MixinFormInvalid:
    def form_invalid(self,form):
        response = super().form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return response

class SinPrivilegios(LoginRequiredMixin, PermissionRequiredMixin, MixinFormInvalid):
    login_url = 'bases:login'
    raise_exception=False
    redirect_field_name="redirecto_to"

    def handle_no_permission(self):
        from django.contrib.auth.models import AnonymousUser
        if not self.request.user==AnonymousUser():
            self.login_url='bases:sin_privilegios'
        return HttpResponseRedirect(reverse_lazy(self.login_url))


class Home(LoginRequiredMixin, generic.TemplateView):
    template_name = 'bases/home.html'
    login_url='bases:login'


class HomeSinPrivilegios(LoginRequiredMixin, generic.TemplateView):
    login_url = "bases:login"
    template_name="bases/sin_privilegios.html"


class IdiomaList(generic.ListView):
    template_name = "bases/idiomas.html"
    model = Idioma
    context_object_name="obj"



class FraseList(generic.ListView):
    template_name = "bases/frases.html"
    model = Frase
    context_object_name="obj"

    def get_queryset(self):
        qs = Frase.objects.all()
        idioma_id = self.request.GET.get("lang")
        if idioma_id:
            qs = qs.filter(idioma__id=idioma_id)
        return qs

app/bases/templates/bases/frases.html
{% extends 'base/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Categorías</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Acciones</div>
          <a class="dropdown-item" href="{% url 'inv:categoria_new' %}"><i class="far fa-calendar-plus"></i> Nueva</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
      {% if not obj %}
      <div class="alert alert-info">No hay Frases</div>
      {% else %}
      <table class="table table-striped table-hover">
          <thead>
              <th>Id</th>
              <th>Idioma</th>
              <th>Frase</th>
              <th class="all">Acciones</th>
          </thead>
          <tbody>
              {% for item in obj %}
              <tr>
                  <td>{{ item.id }}</td>
                  <td>{{ item.idioma }}</td>
                  <td>{{ item.frase }}</td>
                  <td>

                  </td>
              </tr>
              {% endfor %}
          </tbody>
      </table>
      {% endif %}
    </div>
  </div>
{% endblock %}

{% block js_page %}
<script>
  // Call the dataTables jQuery plugin
  $(document).ready(function() {
    $('.table').DataTable();
  });
</script>
{% endblock %}

app/bases/templates/bases/home.html
{% extends 'base/base.html' %}

app/bases/templates/bases/idiomas.html
{% extends 'base/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Categorías</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Acciones</div>
          <a class="dropdown-item" href="{% url 'inv:categoria_new' %}"><i class="far fa-calendar-plus"></i> Nueva</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
      {% if not obj %}
      <div class="alert alert-info">No hay Idiomas</div>
      {% else %}
      <table class="table table-striped table-hover">
          <thead>
              <th>Id</th>
              <th>Idioma</th>
              <th class="all">Acciones</th>
          </thead>
          <tbody>
              {% for item in obj %}
              <tr>
                  <td>{{ item.id }}</td>
                  <td>{{ item.nombre }}</td>
                  <td>
                    <a href="{% url 'bases:frases'%}?lang={{item.id}}" class="btn btn-success btn-circle" role="button"><i class="fas fa-eye"></i></a>
                  </td>
              </tr>
              {% endfor %}
          </tbody>
      </table>
      {% endif %}
    </div>
  </div>
{% endblock %}

{% block js_page %}
<script>
  // Call the dataTables jQuery plugin
  $(document).ready(function() {
    $('.table').DataTable();
  });
</script>
{% endblock %}

app/bases/templates/bases/login.html
{% extends 'base/base.html' %}

{% block side_bar%}{% endblock %}
{% block top_bar %}{% endblock %}
{% block page_content %}{% endblock %}
{% block footer %}{% endblock %}
{% block login %}
<div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Bienvenido</h1>
                    <small class="text-danger">
                        {% if form.errors %}
                            {% for field in form %}
                                {% if field.errors %}
                                    {% for error in field.errors %}
                                        {{ error|escape }}
                                    {% endfor %}
                                {% endif %}
                            {% endfor %}
                        
                            {% if form.non_field_errors%}
                                {% for error in form.non_field_errors %}
                                    {{ error|escape }}
                                {% endfor %}
                            {% endif %}
                        {% endif %}
                    </small>
                  </div>
                  <form class="user" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                      <input type="text" class="form-control form-control-user" id="id_username" name="username" aria-describedby="emailHelp" placeholder="Usuario">
                    </div>
                    <div class="form-group">
                      <input type="password" class="form-control form-control-user" id="id_password" name="password" placeholder="Password">
                    </div>

                    {# { form.as_p } #}

                    <button type="submit" class="btn btn-primary btn-user btn-block">Login</button>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>
{% endblock %}

{% block js_page %}
<script>
  {% if form.errors %}
      {% for field in form %}
          {% if field.errors %}
              {% for error in field.errors %}
                mensaje('{{ error|escape }}','red');
              {% endfor %}
          {% endif %}
      {% endfor %}
  
      {% if form.non_field_errors%}
          {% for error in form.non_field_errors %}
            mensaje('{{ error|escape }}','red');
          {% endfor %}
      {% endif %}
  {% endif %}
</script>
{% endblock %}

app/bases/templates/bases/sin_privilegios.html
{% extends 'base/base.html' %}
{% block page_content %}
    <div class="col-xl-6 col-md-6 mb-6">
        <div class="card border-left-danger shadow h-100 py-2">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
            <div class="col mr-2">
                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                    Usuario: <mark>{{ user.username }}  {{user.get_full_name }}</mark> 
                </div>
                <div class="dropdown-divider"></div>

                <div class="row">
                    <mark>No tiene suficientes privilegios</mark> para cargar opción solicitada.
                    <br>
                    <small>Para poder acceder, debes loguearte con un usuario con privilegios necesarios.</small>

                </div>
                <div class="dropdown-divider"></div>
                <div class="row">
                    <div class="col">
                        <a href="{% url 'bases:home' %}" class="btn btn-success"><span class="fa fa-home"></span> Ir a Inicio</a>
                        <a href="{% url 'bases:login' %}" class="btn btn-success"><span class="fa fa-user"></span> Ingresar con otro Usuario</a>
                    </div>
                </div>
            </div>
            <div class="col-auto">
                <i class="far fa-calendar-plus fa-2x text-gray-300"></i>
            </div>
            </div>
        </div>
        </div>
    </div>
{% endblock %}